[package]
name = "dreadbot"
version = "0.1.0"
authors = ["Brian Carrigan <brian.c.carrigan@gmail.com>"]
edition = "2018"


[dependencies]
reqwest = "0.9.20"
serde = "1.0.100"
serde_derive = "1.0.100"
serde_json = "1.0"
serenity = "0.7.0"
regex = "1"
sha2 = "0.8.0"
lazy_static = "1.4.0"
